# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "2a827c89993fb2f69ccfe881c914520f66101a2a";
      sha256 = "0xnxw1k2w9qnimw7i0f7kf2yr77sygallpj1slzg9l1wfps9jvzn";
    };
  }
]
