# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn, systemd
, patchelf, runCommand }:

let
  jcl = buildGoPackage rec {
    name = "journald-cloudwatch-logs-unstable-${version}";
    version = "2017-08-25";
    rev = "191803533c8bd401be5ad6235bb66bb4c8e6c9ec";

    goPackagePath = "github.com/homecu/journald-cloudwatch-logs";

    src = fetchgit {
      inherit rev;
      url = "https://github.com/homecu/journald-cloudwatch-logs";
      sha256 = "1iik7kawx2pk8rmg4xydfx3plhb092j6gixardzsr1fwphxwwi3w";
    };

    goDeps = ./deps.nix;

    buildInputs = [ systemd ];

    # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
    meta = {
    };
  };
  libPath = stdenv.lib.makeLibraryPath [ stdenv.glibc systemd ];
in runCommand "journald-cloudwatch-logs" {} ''
  mkdir -p $out/bin
  cp ${jcl}/bin/journald-cloudwatch-logs $out/bin
  chmod -R +w $out/bin
  ${patchelf}/bin/patchelf --set-rpath ${libPath} $out/bin/journald-cloudwatch-logs
''
